### ISSUE TITLE
Talk proposal: React Front-end Architecture for Micro-Apps

### ISSUE THREAD

**Issue by maddhruv** [queerjs/queerjs-talk-proposals#10]
### Talk title
React Front-end Architecture for Micro-Apps

### Abstract 
The talk covers designing your react application for a micro apps/services based architecture to react the final goal of Micro Front-end Architectures. The talk also covers the tools to manage the micro apps’ - dependencies, releases and yes, separate teams. We at ClearTax have adopted the micro-apps architecture after 4 years of using the monolithic architecture and have seen healthy growth in our developer experience and releasing processes.

### Your name (and pronouns)
Dhruv Jain (He/Him)

### Location
Based in - Bangalore, India
Would Like to speak in any of - (Barcelona|Stockholm|San\ Francisco)

### Contact Details
Twitter - https://twitter.com/maddhruv
Email - dhruvjainpenny@gmail.com

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by carolstran** [comment]
Closing as mentioned in #9
