### ISSUE TITLE
Talk proposal: React architecture for your app

### ISSUE THREAD

**Issue by maddhruv** [queerjs/queerjs-talk-proposals#11]
### Talk title
Web Workers Empathy

### Abstract 
Web Workers were a boon to JavaScript and Web but after their inception, they have not been modernized with the new JavaScript - Promises (async), writing advanced tests, advance modules/dependencies bundling. The talk covers the ways to modernize web workers - use promises for message/data passing, convert modules and small sets of functions into worker scripts, have more intuitive control over them and how to write tests for your workers or worker scripts.

### Your name (and pronouns)
Dhruv Jain (He/Him)

### Location
Based in - Bangalore, India
Would Like to speak in any of - (Barcelona|Stockholm|San\ Francisco)

### Contact Details
Twitter - https://twitter.com/maddhruv
Email - dhruvjainpenny@gmail.com

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by carolstran** [comment]
Closing as mentioned in #9
