### ISSUE TITLE
Talk proposal:  Handling Large Client Side Data Sets

### ISSUE THREAD

**Issue by maddhruv** [queerjs/queerjs-talk-proposals#12]
### Talk title
Handling Large Client-Side Data Sets

### Abstract 
Handling large data sets is now easier for your web applications - push the data to the client and store in the IndexedDB but is it really so easy for your User Experience. Here at ClearTax, we have thousands of invoices/bills documents to process and reading and writing this huge data to/from the IndexedDB is a very heavy job limiting in the Maximum IPC Message Call passing and not blocking the main thread. The talk covers up the same problem and how to easily solve this problem of managing huge data sets - fetching and processing on the browser using web workers and Message Passing protocols.

### Your name (and pronouns)
Dhruv Jain (He/Him)

### Location
Based in - Bangalore, India
Would Like to speak in any of - (Barcelona|Stockholm|San\ Francisco)

### Contact Details
Twitter - https://twitter.com/maddhruv
Email - dhruvjainpenny@gmail.com

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by carolstran** [comment]
Closing as mentioned in #9
