### ISSUE TITLE
Talk proposal: Adventures in WHOIS

### ISSUE THREAD

**Issue by bitcynth** [queerjs/queerjs-talk-proposals#13]
### Talk title
Adventures in WHOIS

### Abstract 

Some of my projects and experiences with relation to the WHOIS protocol.

### Your name (and pronouns)
Cynthia Maja Revström
She/her

### Location
Stockholm, Sweden (I live there and I want to speak there)

### Contact Details
https://cynthia.re
https://twitter.com/bitcynth
me@cynthia.re
Email me if you require a phone number.

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by SaraVieira** [comment]
👋

Adding you now!

So happy you speaking :D

**Comment by SaraVieira** [comment]
Added 🎉 https://queerjs.com/stockholm 🎉

**Comment by bitcynth** [comment]
Yay :)

**Comment by carolstran** [comment]
Thank you so much for speaking last night @bitcynth! Heard it went really well 💞 I'm going to close this issue now, but thanks again 🤩
