### ISSUE TITLE
Talk proposal: Helping Your Compiler Help You

### ISSUE THREAD

**Issue by robotlolita** [queerjs/queerjs-talk-proposals#15]
### Talk title

Helping Your Compiler Help You

### Abstract 

Despite all of the great advances in the last years, computer resources are still limited. Modern JavaScript compilers do an amazing job of using them efficiently, but in doing so they also make it very difficult to know if using a particular feature will cause a performance bottleneck—and if you need to care about performance, this can be pretty painful. Luckily there are some guidelines that you can use when writing your programs to stay on the bright side of the compiler's heuristics!

This talk will give you some guidelines and tools to use when performance matters for your project. Guidelines are general, but tools will be specific to v8 (Node.js, Chrome, and Electron).

### Your name (and pronouns)

Quil (they/them)

### Location

Stockholm (I live here and would like to speak here)

### Contact Details

queen@robotlolita.me, https://robotlolita.me/ (my Twitter is private so I guess it makes sense to link to my website instead)

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by carolstran** [comment]
Hey @robotlolita 👋 Thanks for submitting a talk 💕 Unfortunately the lineup for our Stockholm meetup in October is full. 

So there are two options: 1) We can put you on the waitlist and you'll be first in line for our next Stockholm meetup or 2) We have a meetup in Barcelona on September 4 and we're still looking for speakers if you're interested. We'd be able to pay for your flights (no pressure though, of course).

Let us know what you think. Either way, we'd love to have you at a future QueerJS 😊

**Comment by robotlolita** [comment]
Ah, September is too close for me (no time to prepare), you can put me in the wait list

**Comment by carolstran** [comment]
Ok will do. Thanks for letting us know!

**Comment by avilene** [comment]
@robotlolita would you still be up for giving this talk? I know its a little short notice.

**Comment by robotlolita** [comment]
@avilene ah, yes.

**Comment by SaraVieira** [comment]
I AM ON THIS!!

DANKE

**Comment by SaraVieira** [comment]
Hey!

So we do need your twitter, it can still link to your website if you want to but we need to use the twitter photo as we use the photo, is this okay?

**Comment by SaraVieira** [comment]
I added you with a link to your website: https://queerjs.com/stockholm

Thank you again!

**Comment by carolstran** [comment]
Thank you so much for speaking last night @robotlolita! Heard it went really well 💞 I'm going to close this issue now, but thanks again 🤩
