### ISSUE TITLE
Talk proposal: Making side projects for video games

### ISSUE THREAD

**Issue by joshhunt** [queerjs/queerjs-talk-proposals#16]
### Talk title

Making side projects for video games (title could be improved) 😅

### Abstract 

Over the past 3 years, I've kept myself busy building companion websites for Bungie's video game Destiny on the side, with [DestinySets.com](https://DestinySets.com) being my biggest. I will talk about my journey of developing these side projects, building a community site in the open, and how awesome it is for video games to have official APIs.

### Your name (and pronouns)

Josh Hunt (he/him)

### Location

I live in London, but I don't mind travelling

### Contact Details

twitter.com/joshhunt

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by carolstran** [comment]
Looks excellent thank you 😍 Re: Our twitter conversation, we already have you up on the website!

🎉 https://queerjs.com/london/ 🎉
