### ISSUE TITLE
Talk proposal: Combining history of art and frontend development

### ISSUE THREAD

**Issue by enbee81** [queerjs/queerjs-talk-proposals#17]
### Talk Title
Combining history of art and frontend development

### Abstract 
You may think, art history and frontend development do not have much in common. Well, you may be surprised.
Some of the problems we have to deal with today were discussed in art history long before the invention of the Internet. Also, the skills needed to analyze a piece of art correctly show significant similarity to the capabilities required to implement modern layouts with CSS. Using three paintings from different eras, I will explore various aspects of UX engineering.
This talk will show you how to analyze a static layout by looking beyond pixels. Instead, you will understand why a given design works the way it does and translate this to modern CSS.

### Your name 
Nils Binder (he/him)

### Location
I'm based in Bochum, Germany. I don't have a specific meetup that I planned on attending. I don't have any trouble traveling. So I can give the talk basically anywhere. Depending on the distance, I would need assistance. 

### Contact Details
e-mail: nils.binder@9elements.com
twitter: [supremebeing09](https://twitter.com/supremebeing09)

### Code of Conduct

- [x]  I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by carolstran** [comment]
Hey @enbee81 👋 Thanks for submitting a talk 😍 Turns out there's a chance we might have a QueerJS in Bochum (around the same time as RuhrJS). Nothing is set yet, but I should know more by the end of next week. Is it alright if we get back to you then?

**Comment by enbee81** [comment]
Sure sounds great. Only thing is, I gave this talk two weeks ago at PottJS here in Bochum. So maybe it is a little redundant.

**Comment by carolstran** [comment]
Hey @enbee81, sorry about this! I had the best intentions for something in Bochum this year but then I started a new job this month 🤪

We're already planning our 2020 events and it's looking like we'll have a QueerJS in Cologne sometime in Q1 (probably March, but depends on a few factors) and also an event in Munich around the same time as JS Kongress (mid-April). If you'd be interested in either event, we'd love to have you! I can also get back to you once we know more specifics, but thought I'd at least put it on your radar 😄 We'll most likely also do another Berlin event and I'm very determined to do one in Bochum around RuhrJS 2020 so there are options if Cologne or Munich don't work.

Anyway, thanks again for wanting to be part of this and we hope to have you on stage very soon 💛

**Comment by enbee81** [comment]
Thanks for your kind words, and don't be sorry. In fact, I'm a little relieved, that there was no queerJS this Fall, as I had so much going on over the last weeks, I am not sure I would have had time to attend. 

But now I'm very excited about next year. I'd still love to speak at one of the events. Cologne is quite close. Maybe I would stay there for one night, so I have time to talk to other attendees after the talks. I'm also happy to drive to Munich or Berlin. For Munich, I'd need transportation and accommodation. In Berlin, I have some friends where I could stay. 

Of course, Bochum ist where I am from and therefore really close, but around the time when RuhrJS takes place, there are always three birthdays of people that are very important to me. So this may be the wrong time.

Hope to see you soon.

**Comment by carolstran** [comment]
Updated the labels to reflect that you'll be speaking in February 🎉

**Comment by carolstran** [comment]
:wave: @enbee81, I've said this on like 5 different platforms now but thank you so much for speaking at our first QueerJS Cologne! Closing this issue for now, but looking forward to seeing you around Bochum soon 🤸‍♀  Also if you have any feedback about the meetup last night, please feel free to reach out to any of the organizers (myself included) here or on Twitter or Discord 😊
