### ISSUE TITLE
Talk proposal: Understanding Technical Decision Making

### ISSUE THREAD

**Issue by raphaeleidus** [queerjs/queerjs-talk-proposals#18]
### Talk title
Understanding Technical Decision Making

### Abstract
A walk through how I think about technology and architecture decision making as a leader and how you can quantify your own rubric for decision making to feel more confident in your decisions. Technology decisions can generally be thought of as optimization problems, choosing 1 strength over another weakness. I will walk through several different things that I sometimes consider and why the landscape of considerations should change depending on what it is you are working on.

### Your name
Raphael Eidus (He/Him)

### Location
reside in New York City
interested in speaking in SF or anywhere else after the october 8 date

Might need limited travel assistance.

### Contact Details
twitter: @raphaelcodes

### Code of Conduct

- [X] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by carolstran** [comment]
👋 @raphaeleidus! Nice to see you here, so happy you submitted a talk 🎉

I labeled you as SF for now, but question: Would you be interested in speaking at the upcoming NYC event? It looks like it'll also be on November 2 (or around then).

**Comment by raphaeleidus** [comment]
I would love to speak in NYC in November. I didn't see it on the schedule yet.

**Comment by carolstran** [comment]
We're waiting for the venue/local organizers to confirm the date before we put it on the website 😊 Adding an NYC label as well then 🗽 We'll get back to you as soon as we know the details!

**Comment by carolstran** [comment]
Hey hey @raphaeleidus, so we're still working on getting the website up but if you'd be up for speaking at QueerJS NYC on November 2 then we'd love to have you! Just let me know ✨

**Comment by raphaeleidus** [comment]
I am 100% in!!!

**Comment by carolstran** [comment]
Woooo! Can't wait to have you!

Pinging @SaraVieira so she knows to add you to the website once it's up 😁

**Comment by SaraVieira** [comment]
Heeey

You have been added! Happy to have you speak 🎉

https://queerjs.com/new-york

**Comment by carolstran** [comment]
Thank you so much for speaking over the weekend @raphaeleidus! Heard it went really well 💛 I'm going to close this issue now, but thanks again 🤩
