### ISSUE TITLE
Talk proposal: Git Workflow Etiquette

### ISSUE THREAD

**Issue by irmerk** [queerjs/queerjs-talk-proposals#19]
### Talk title
Git Workflow Etiquette: Repository Organization for Clean Codebases

### Abstract 
Version control with git provides for powerful collaboration, whether it be a tight-knit tech team or a distributed network in an open source format. Still, proper care must be taken. Good quality software consists of, among other things, code which is robust, resilient, secure, and performant. These attributes are achievable by maintaining a foundation of good quality code and a solid history of documentation. Anyone should be able to join the process and easily figure out and track the status of the project.

### Your name (and pronouns)
Jolene Langlinais (she/her)

### Location
New York, NY, USA
I would be happy to speak in San Francisco, or any other city you host again in the future. I would require travel assistance.

### Contact Details
https://jolenelanglinais.com/ (link to this)
https://twitter.com/jolanglinais
https://github.com/irmerk
jolenelanglinais@gmail.com

### Code of Conduct
- [X] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by carolstran** [comment]
Hey hey @irmerk, thank you so much for submitting a talk 💕 We're still working on getting the website updated, but there will actually be a QueerJS in NYC on November 2. And since you're based in New York... I'm wondering if you'd be up for speaking?

If so, then we'd love to have you! Just let me know 🗽

**Comment by SaraVieira** [comment]
I continued the DM on twitter and added Jolene to NY 🌈

**Comment by irmerk** [comment]
Yes, happy to speak at NYC!

**Comment by carolstran** [comment]
Thank you so much for speaking over the weekend @irmerk! Heard it went really well 💛 I'm going to close this issue now, but thanks again 🤩
