### ISSUE TITLE
Talk proposal: "building a brand-new fifteen-year-old game"

### ISSUE THREAD

**Issue by quarterto** [queerjs/queerjs-talk-proposals#2]
### Talk title

"building a brand-new fifteen-year-old game"

### Abstract 

when my dad first showed me the `View Source` button on Internet Explorer my second thought after "why so many tables" was "okay so can i do this to Pokemon FireRed?" and of course no i couldn't but fastforward a few years and some people on some forums with names like `xXDittoLuvr69Xx` have done the reverse engineering so i don't have to and now i'm building the Pokemon game i always wanted and let me tell you, if i never have to look at a hex editor again i'll be a happy enby

### Your name

Bren Brightwell (they/them)

### Location

based in London, would like to speak at London

### Contact Details

twitter (link to this please): [`@quarterto`](https://twitter.com/quarterto)
email: [bren@153.io](mailto:bren@153.io)

### Code of Conduct

 - [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by carolstran** [comment]
You're our first talk submission @quarterto, thank you so much! I added a `London` label since you'd like to speak in London 😊

**Comment by SaraVieira** [comment]
Thank you so much bren!

I believe we met in berlin! I am adding you to the website now!

Thank you so much for making QueerJS even more amazing!

We will make sure to get you something :)

**Comment by SaraVieira** [comment]
🎉🎉 https://queerjs.com/london/ 🎉🎉

@quarterto Mind if we announce you?

**Comment by quarterto** [comment]
> I believe we met in berlin

yes briefly at jsconf karaoke 😊 

> Mind if we announce you?

nope!!! aaaaaa

i'm gonna close this issue?

**Comment by carolstran** [comment]
Hey @quarterto, I'm going to open the issue again and we'll wait to close it until after you've presented in London. That way, everything is a bit more transparent overall 😊 Hope you don't mind!
