### ISSUE TITLE
Talk proposal: Presenting and discovering our identities through social software

### ISSUE THREAD

**Issue by suchipi** [queerjs/queerjs-talk-proposals#20]
### Abstract 

When we interact with people through the internet, the ability to customize our profile or avatar helps both describe and shape our identities. From Twitter bios to Tumblr themes to full-on virtual reality avatars, this talk explores the interplay between presentation and self-definition, and looks into the psychology behind using an online avatar to describe and understand who we are.

### Your name (and pronouns)

Lily Scott, She/her

### Location

I'm located in Denver and am interested in speaking at the San Francisco QueerJS in November, at the Webflow office. I work for Webflow, so they can pay to bring me out there.

### Contact Details

@suchipi on Twitter and Github
me@suchipi.com

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by SaraVieira** [comment]
Thank you so much! I will add you to the website tomorrow 🥰

**Comment by carolstran** [comment]
Thank you so much for speaking over the weekend @suchipi! Heard it went really well 💛 I'm going to close this issue now, but thanks again 🤩
