### ISSUE TITLE
Talk proposal: The Front End is for Everyone!

### ISSUE THREAD

**Issue by eheron** [queerjs/queerjs-talk-proposals#21]
### Talk title
The Front End is for Everyone!

### Abstract 
This talk will be an overview of how to build accessible front ends specifically as it relates to user's that use screen readers to navigate and interact with webpages. It will provide an overview on what it means for an application to be accessible. What a screen reader is and what it does, as well as a quick demo of screen reader usage to provide additional clarity. I will talk about aria tagging and the what the categories within aria mean. And some examples to clarify what purpose aria tagging serves. As for why I'm doing this, the short of it is I believe in the promise of an internet that is for everyone. I'm a minority and I know what it is like to be in spaces that aren't inclusive or go out of the way to be blatantly exclusive. And I never want to build a web app (or anything really) that makes someone feel that way because its not set up to be used by anyone and everyone. 

### Your name (and pronouns)
Elise Heron  she/her/hers

### Location
Im based in Denver and would like to speak at the San Francisco conference please.

### Contact Details
Professional Email: elise.heron@validity.com
Personal Email: e.heron00@gmail.com
Twitter: @thedarkestknght (I'm cool with y'all linking to it)
Personal Github: thedarkestknight

### Code of Conduct

- [:white_check_mark: ] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by carolstran** [comment]
Hey hey @eheron, thank you for submitting a talk 😍

Unfortunately, our SF lineup is already full but we'd love to put you on our waitlist and keep you in mind for future US events! Just let me know if that's ok with you 😊

**Comment by carolstran** [comment]
Hey again @eheron 👋 Would you be interested in potentially speaking at our NYC meetup on the same day? Or would you rather wait until we have another edition of the SF meetup?

**Comment by eheron** [comment]
Hi @carolstran! Thanks for letting me know. It's alright you don't have to put me on the waitlist, but I would like to be kept in mind for future US events. As for the NYC meetup I think it is best if I hold off for now. But thanks again for reaching out.

**Comment by carolstran** [comment]
Definitely @eheron 😊 We'll let you know when we have an idea of what other US events are happening next (likely in 2020) 🎉
