### ISSUE TITLE
Talk proposal: Bookmarklets: How I make your browser work for you

### ISSUE THREAD

**Issue by mdjmoore** [queerjs/queerjs-talk-proposals#22]
### Abstract 

A quick look at how to make bookmarklets in your browser and some handy ones to have around when developing

### Location

Based in Toronto, Ontario, Canada and would like to speak at the Toronto event

### Contact Details

You can email me at meagan[at]mdjm.io , contact me through twitter @_mdjm , or my github at mdjmoore.

Please feel free to link to my twitter or website: mdjm.io

### Code of Conduct

- [X] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by carolstran** [comment]
Hey @mdjmoore 👋 Thanks for submitting a talk - that makes you our first Toronto speaker 🇨🇦 🎉 

I'll add you to the website asap!

**Comment by carolstran** [comment]
Alright you're live! https://queerjs.com/toronto 🚀

**Comment by carolstran** [comment]
👋 @mdjmoore, thank you for giving a talk at our first Toronto meetup! I heard it went very, very well. If you have any feedback about the event, feel free to drop that here or you can also ping any of the organizers (myself included!) on Discord. 

Closing this for now 🌈 🤸‍♀ 🎉
