### ISSUE TITLE
Talk proposal: Making Techno with Ancient Algorithms (and JS)

### ISSUE THREAD

**Issue by caycefischer** [queerjs/queerjs-talk-proposals#23]
### Talk title
Making Techno with Ancient Algorithms (and JS)

### Abstract 

This talk will be about using javascript to prototype an electronic drum computer, that makes use of a 2000-year-old algorithm from ancient Greece to generate musical rhythms.

### Your name (and pronouns)
Cayce Fischer (she/her)

### Location
Based in Toronto, and I'd like to speak in Toronto. No travel necessary!

### Contact Details

Best way to contact me is over email at cayce@autotectonic.com. You can link my twitter on your page: http://twitter.com/autotectonic 

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by carolstran** [comment]
Hey @caycefischer 👋 Thanks for submitting a talk for our first Toronto meetup 🇨🇦 🎉 The topic looks really cool I hope they have a live stream 😏 😄 

I'll add you to the website asap!

**Comment by carolstran** [comment]
You're live! https://queerjs.com/toronto

**Comment by carolstran** [comment]
👋 @caycefischer, thank you for giving a talk at our first Toronto meetup! I heard it went very, very well. If you have any feedback about the event, feel free to drop that here or you can also ping any of the organizers (myself included!) on Discord. 

Closing this for now 🌈 🤸‍♀ 🎉
