### ISSUE TITLE
Talk proposal: Toronto Open Data and You!

### ISSUE THREAD

**Issue by sidramatik** [queerjs/queerjs-talk-proposals#25]
Toronto Open Data and You!

### Abstract 
This year, we're celebrating 10 years of open data in Toronto! What's it all about and how does it impact the city? How has the program matured and what are our priorities? What can developers leverage from our data portal? How do you get involved? You'll learn the answers to these and more!

Sidra Mahmood, @sidramatik
Pronouns: she/they

### Location

Local!

### Contact Details

@sidramatik (Twitter, Github)
sidramatik.com
hello@ardisdigital.com

### Code of Conduct

- [X] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by carolstran** [comment]
👋 @sidramatik, thank you so much for submitting a talk to QueerJS Toronto! This talk sounds rad. 

I'll add you to the website now 🎉

**Comment by carolstran** [comment]
You're on the website @sidramatik 🍡 🍬 🍰  https://queerjs.com/toronto

**Comment by carolstran** [comment]
👋 @sidramatik, thank you for giving a talk at our first Toronto meetup! I heard it went very, very well. If you have any feedback about the event, feel free to drop that here or you can also ping any of the organizers (myself included!) on Discord. 

Closing this for now 🌈 🤸‍♀ 🎉
