### ISSUE TITLE
Talk proposal: The Importance of Building and Having a Community Especially while Transitioning into Tech

### ISSUE THREAD

**Issue by stefi23** [queerjs/queerjs-talk-proposals#26]
### Talk title
The Importance of Building and Having a Community Especially while Transitioning into Tech.

### Abstract 

I want to talk about the importance of people coming together and offering their support to each other.  In today’s world there is a lot of individualism and going through a career change can be frightening, as well as through other difficult situations. Although I haven't yet changed my job I want to share what I've learned so far through this journey and how thanks to the support of the community I have I overcome every challenge encountered so far. 

### Your name (and pronouns)

Stefania Rosca (she/her)

### Location

Based in Barcelona and would like to speak in Paris. I do need travel assistance.  

### Contact Details

Email: stefania.rosca2309@gmail.com
Twitter: @Stefania_Rosca 
https://github.com/stefi23

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by carolstran** [comment]
👋 @stefi23, thank you for submitting a talk for Paris! I loooove this topic - I also recently changed to tech and it's so encouraging (and important) to hear these perspectives.

I'll add you to the website now 🥖 

Pinging @SaraVieira re: travel costs because she'll know more about handling that 😇

**Comment by carolstran** [comment]
Alright you're live!

🇫🇷 https://queerjs.com/paris 🇫🇷

**Comment by stefi23** [comment]
This is so exciting! 😊 Thank you, @carolstran 🙌 Transitioning into tech is a scary thing to do but so worth it, right?

**Comment by stefi23** [comment]
Hi, @SaraVieira 😊What is the procedure regarding the travel costs? Thanks!

**Comment by SaraVieira** [comment]
Hey!

Let me talk to the organizer of the Paris community, @pducolin if this is a talk she would like to see to make sure it doesn't crash with any talk 

Seeing you are from Barcelona, travel shouldn't be an issue, you will have to stay in a bad hotel probably since Paris is super expensive 😭

**Comment by stefi23** [comment]
Thanks, @SaraVieira! No worries! I know Paris is expensive. I'm good with a bad hotel too 😉

**Comment by pducolin** [comment]
Great topic, looking forward to hear it!

**Comment by SaraVieira** [comment]
Awesome! Can you tell me your dates so we can get a trip set up?

**Comment by SaraVieira** [comment]
Is this flight okay? https://kay.ac/8cz-v5

**Comment by stefi23** [comment]
This flight is perfect, @SaraVieira! Should I send you some additional info? My full name is Stefania Rosca.

**Comment by SaraVieira** [comment]
@stefi23 How averted are you to staying in a shared hostel room?

**Comment by SaraVieira** [comment]
Can you send me all your info to this email: hey@iamsaravieira.com?

![Screenshot 2019-11-11 at 18 17 46](https://user-images.githubusercontent.com/1051509/68606846-9d1e0680-04af-11ea-8a4c-1f2ee83f4b0a.png)

**Comment by stefi23** [comment]
I've just emailed you the info. Thanks!

**Comment by stefi23** [comment]
Hi, @SaraVieira Did you receive my email? Thanks!

**Comment by SaraVieira** [comment]
All done!

Sorry, I was waiting to be paid 😂

**Comment by stefi23** [comment]
Thank you  🙌 See you soon!

**Comment by carolstran** [comment]
👋 @stefi23, thank you for giving a talk at our first Paris meetup! I heard it went very, very well. If you have any feedback about the event, feel free to drop that here or you can also ping any of the organizers (myself included!) on Discord. 

Closing this for now 🌈 🤸‍♀ 🎉

**Comment by stefi23** [comment]
Thank you, @carolstran  🙌I'm super happy to hear this! The event was great!
