### ISSUE TITLE
Talk proposal: The art of building positive culture 

### ISSUE THREAD

**Issue by tiltedcanvas** [queerjs/queerjs-talk-proposals#27]
### Talk Title
The art of building positive culture 

### Abstract 
What happens when a space you frequent turns (or already is) toxic and difficult to navigate? I'll talk to you about how to help build a positive culture that embodies diversity and inclusion. 

### Name
Jasmine Carbone

### Location
Based in Toronto, Ontario, Canada and would like to speak at the Toronto event

### Contact Details

You can email me at jasmine@tiltedcanvas.com
Or contact me through twitter @tiltedcanvas, or my github at tiltedcanvas

Please feel free to link to my twitter or website: www.tiltedcanvas.com

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by carolstran** [comment]
Hey @tiltedcanvas, thanks for submitting a talk for QueerJS Toronto! Just talked to the local organizers and we're good to go! I'll add you to the website now 😊

**Comment by carolstran** [comment]
👋 @tiltedcanvas, thank you for giving a talk at our first Toronto meetup! I heard it went very, very well. If you have any feedback about the event, feel free to drop that here or you can also ping any of the organizers (myself included!) on Discord.

Closing this for now 🌈 🤸‍♀ 🎉
