### ISSUE TITLE
Talk proposal: Technical Debt: Opening your eyes on what you don’t want to see, and how to act on it

### ISSUE THREAD

**Issue by jonathansalamon** [queerjs/queerjs-talk-proposals#30]
### Talk title
Technical Debt: Opening your eyes on what you don’t want to see, and how to act on it

### Abstract 
This talk will start by explaining what is technical debt and why you should care about.
Then, we will see how to measure it, the discoveries you might find, and how to act on it.
We will provide you with a concrete example of what the Android Team has done at Dashlane in order to get back in control with the technical debt of a 5 years old project.

From the basic of measuring the technical debt of your project to a full integration into your release process, let's cover it all!

### Your name (and pronouns)
Jonathan SALAMON

### Location
I am based in Paris, but I want to talk at QueerJS Lisbon.
Dashlane will cover the expenses.

### Contact Details
jonathan@dashlane.com
Twitter: J_TheFrench

### Code of Conduct

- [ X ] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by SaraVieira** [comment]
This is awesome!! Thank you so much!!

I will add you to the website tomorrow 🇵🇹🇵🇹♥️

**Comment by jonathansalamon** [comment]
Thanks a lot ♥️

**Comment by jonathansalamon** [comment]
Hello @SaraVieira , please tell me when my talk will be added to the website, because I would like to communicate about it. I plan to do one single post that will mention the 2 upcoming events (in Paris and Lisbon).

Thanks

**Comment by carolstran** [comment]
Sorry about that @jonathansalamon! Just merged a PR that added you so you're on there now. Thanks for wanting to be part of this 🤗 https://queerjs.com/lisbon

**Comment by carolstran** [comment]
👋  @jonathansalamon, thank you for giving a talk at our first Lisbon meetup! I heard it went well. If you have any feedback about the event, feel free to drop that here or you can also ping any of the organizers (myself included!) on Discord.

Closing this for now 🌈 🤸‍♀ 🎉
