### ISSUE TITLE
Talk proposal: How to make accessibility important at your workplace, and why you should

### ISSUE THREAD

**Issue by davidbailey00** [queerjs/queerjs-talk-proposals#32]
### Talk title

How to make accessibility important at your workplace, and why you should 

### Abstract 

Designing and programming with accessibility in mind is essential for the millions of disabled people who use the web - yet so many businesses ignore accessibility when it comes to their products, be it out of fear, cost, or even just unawareness. In this talk, I'll discuss how I made accessibility a bigger priority at my workplace (Memiah Limited), and why you should do the same.

### Your name (and pronouns)

David Bailey (they/them)

### Location

Based in United Kingdom, near London

Don’t have a major preference of where to speak - Cologne or Munich would be great :)
Flight reimbursement would be appreciated

### Contact Details

davidbailey00 on GitHub/Twitter
davidbailey00@outlook.com
DavidBailey#9253 @ Discord

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by carolstran** [comment]
👋 @davidbailey00, thanks for submitting a talk to QueerJS and especially one of our German events! Let me coordinate with the other organizers and let you know which event might be better. Are you available for both dates?

**Comment by davidbailey00** [comment]
Yes, I should be available for either date!

**Comment by carolstran** [comment]
Hello again @davidbailey00 👋 We spoke about it as a team and if possible, we'd love to have you at the Cologne meetup! We can pay for your flights 😊 

Let us know if that still works for you!

**Comment by davidbailey00** [comment]
Awesome, that sounds great!!

Just to check, is my talk expected to be given in English or German? I have assumed English since that seems to have been the case for past meetups - is that correct?

**Comment by carolstran** [comment]
Yes English! Sorry if we didn't make that clear.

Can I add you to the Cologne website? 😁

**Comment by davidbailey00** [comment]
Sure! You can use the profile pic on my GitHub profile :)

**Comment by carolstran** [comment]
The way the website is now, it pulls your photo from your Twitter profile. Is that ok?

**Comment by davidbailey00** [comment]
Ah sure, no worries!

**Comment by carolstran** [comment]
You're on the website 🎉 queerjs.com/cologne 

As far as arranging travel reimbursement, @SaraVieira can help with that 😊

**Comment by davidbailey00** [comment]
Hi @SaraVieira, I've messaged you on Discord re: travel reimbursement :)

**Comment by carolstran** [comment]
👋 @davidbailey00, thanks again for giving a talk last night! It was great and it was also nice to meet you irl. If you have any feedback about the event, feel free to drop that here or you can also ping any of the organizers (myself included!) on Discord or Twitter.

Closing this for now 🌈 🤸‍♀ 🎉

**Comment by davidbailey00** [comment]
Thank you, it was lovely to see everyone and I really enjoyed the meetup!
