### ISSUE TITLE
Talk proposal: Re-imagining creativity: The impact of technology in art

### ISSUE THREAD

**Issue by biancagst** [queerjs/queerjs-talk-proposals#36]
### Talk title
Re-imagining creativity: The impact of technology in art
### Abstract 

I am the founder of a start-up that allows anyone to create personalized original paintings using AI.

I would like to discuss the future of art and the use of technology in art. Speak a little about our technology as well as other technologies that are being used to create other forms of art. (i.e. music)

Explore artistic expression, the creative process of a person vs the creative process of an AI. And close with some open questions on the meaning of art and its impact.

 
### Bianca Gostin

- [x ] This will be my first tech talk

### Contact Details
bianca.gostin@smartist.fr 
+33667632473
Insta: @bianca.gst   and @smartistai 

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by SaraVieira** [comment]
@pducolin
