### ISSUE TITLE
Talk proposal: Type-safe, functional React with ReasonML

### ISSUE THREAD

**Issue by gbogard** [queerjs/queerjs-talk-proposals#39]
### Abstract 

This is a small introduction to ReasonML, a language and toolchain that brings the soundness and expressivity of OCaml to the Javascript world. It will explain what ReasonML is, and showcase some of its interesting features, focusing on type-safety and functional composition.
It assumes some familiarity with React or another expressive MVVP library, but requires not prior knowledge of ReasonML :) 

### Your name (and pronouns)

Guillaume Bogard, he/him

- [ ] This will be my first tech talk

### Location

Remote / Paris / anywhere in Europe with affordable travel from Lille 😄 

### Contact Details

Twitter: @bogardguillaume
E-mail: hey@guillaumebogard.dev
Also on QueerJS' Discord

### Code of Conduct

- [X] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by SaraVieira** [comment]
@gbogard  

Since this is online I would need to do a tech check to get the live stream working properly.

Do you mind booking a time here?
https://calendly.com/saravieira/tech-check

**Comment by gbogard** [comment]
@SaraVieira sure thing!

**Comment by gbogard** [comment]
Here are the slides of the talk :) 
https://github.com/gbogard/queerjs-reasonml-talk
