### ISSUE TITLE
Talk proposal: Why 🙏 Ain't High-Five, but 🏳️⍰ is Pride

### ISSUE THREAD

**Issue by andytuba** [queerjs/queerjs-talk-proposals#40]
### Talk title

Why  🙏Ain't High-Five, but 🏳️⍰ is Pride

### Abstract 

A brief history of encoding culture(s) and identity into Multi-Person Grouping Emojis; or, why isn't my trans pride flag showing up right on my Twitter display name?

This could be a 5, 10, 20, or 45 minute talk.

### Your name (and pronouns)

andytuba (he/him or they/them)

- [ ] ~This will be my first tech talk~

### Location

I'm located in San Francisco and would like to speak at an online event or in SF.

### Contact Details

andytuba.com
andytuba@andytuba.com
twitter.com/andytuba

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by SaraVieira** [comment]
Hey!

For now and untill next year we are only doing online events would that be okay? 

I know you marked it there but mostly to know if you would like to stay open after the online event for an in person one when the world isn't on fire 🙏🙏

**Comment by andytuba** [comment]
Hi @SaraVieira! Yes, online is just fine, thank you for asking. I also look forward to attending and potentially speaking at an in-person event!

**Comment by SaraVieira** [comment]
Amazing! I will add your to the website now :)

Can you make the talk 10m? We are kinda full

**Comment by SaraVieira** [comment]
Just added you to the website:

🎉🎉https://queerjs.com/online-2020-16🎉🎉


Gonna leave this open for the next SF one :)

**Comment by andytuba** [comment]
10 minutes? Can do!

🙌🙌🙌🙇‍♀️🙇‍♀️🙇‍♀️

**Comment by SaraVieira** [comment]
@andytuba 

Since this is online I would need to do a tech check to get the live stream working properly.

Do you mind booking a time here?
https://calendly.com/saravieira/tech-check

**Comment by andytuba** [comment]
Scheduled! I'm @andytuba on Skype, too

**Comment by SaraVieira** [comment]
Thank you!
