### ISSUE TITLE
Electronic Tales: computer culture for everyone

### ISSUE THREAD

**Issue by OfficierAzarov** [queerjs/queerjs-talk-proposals#41]
### Abstract 

We want to talk about our community project, _Electronic Tales_, which will be based on a learning platform aimed at junior developers. By showing our project, we will discuss topics such as what is computer culture, normativity in IT and the toxic myth of "the super geek". Our goal is to create a "coding safe space": a space where junior developers feel included and free to share their insecurities, tips and knowledge.

### Your name (and pronouns)

Elisabeth Fainstein (she/he) - will do the presentation,
Claire Heude (she) - will do the presentation, 
Pauline Artemenko (she) - member of the team, 
Jean Heude (he) - member of the team.

- [x] This will be my first tech talk

### Location

We are based in Tours, France. We want to attend QueerJS on the Internet.

### Contact Details

Elisabeth Fainstein : elisabethfainstein@gmail.com, +336 20 93 52 54.
Twitter : @Officier_Azarov

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by pducolin** [comment]
Hi Elisabeth, thank you for adding your talk proposal!
Is it the same talk you were planning to do at QueerJS Paris?

**Comment by OfficierAzarov** [comment]
Hi Paola! Yes, it's the same one! Is it okay for you?

**Comment by pducolin** [comment]
Oh yes!

**Comment by SaraVieira** [comment]
Just added you to the website:

🎉🎉https://queerjs.com/online-2020-16🎉🎉


Should I also add Claire? Can you tell me what her twitter is?

**Comment by OfficierAzarov** [comment]
HI @SaraVieira! Thank you for adding me.
Yes, could you add Claire, please? She's just created a twitter account for the occasion: @MondayHazard1

**Comment by SaraVieira** [comment]
Of course! Thank her for making the account from me

I will add her today :)

**Comment by SaraVieira** [comment]
Sorry, had the weekend but just added her now :)

**Comment by SaraVieira** [comment]
@OfficierAzarov 

Since this is online I would need to do a tech check to get the live stream working properly.

Do you mind booking a time here? IT would be even better if claire could join
https://calendly.com/saravieira/tech-check

**Comment by OfficierAzarov** [comment]
Hi @SaraVieira! Sure, no problem. What is your time zone? I'd hate to make you get up too early or stay up too late :)

**Comment by SaraVieira** [comment]
Don't worry, all the times in that link are set by me :)

I am in the berlin timezone, if no time works for you let me know :)

**Comment by OfficierAzarov** [comment]
Perfect! Thank you so much!
