### ISSUE TITLE
Talk proposal: Making things for fun (but maybe not for profit)

### ISSUE THREAD

**Issue by sporeball** [queerjs/queerjs-talk-proposals#43]
### Talk title

Making things for fun (but maybe not for profit)

### Abstract 

the Patreon page i set up as a way to make a profit from my open-source projects has brought in almost no money in the nearly two years since its creation - but that's okay, because programming can be fun even if nobody knows you're doing it!
this is a lightning talk about three methods i use to go about making fun things, with three of my projects - naz, muffy, and victus - as case studies.

### Your name (and pronouns)

sporeball (she/her)

- [x] This will be my first tech talk

### Location

California, USA (applying for QueerJS @ The Internet)

### Contact Details

Twittter: [@sporeball](https://twitter.com/sporeball)

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by pixelyunicorn** [comment]
omg this talk sounds amazing, and i would love to have you speak at our next meetup on march 30 at 11:30am PDT!

would you be available to give your talk then, and are you cool if we added this to the website?

**Comment by sporeball** [comment]
feel free to add it to the website!!
i'm going to end up having classes that day, and my internet can be spotty at times regardless - so i was hoping i'd be able to submit a pre-recorded stream in a few weeks' time, if that's okay?

**Comment by pixelyunicorn** [comment]
absolutely, pre-recorded talks are more than welcome! there may be a q&a section afterwards, but if you aren't available for that then we work without it :)

**Comment by pixelyunicorn** [comment]
added you to the website!

**Comment by pixelyunicorn** [comment]
Thanks for getting us your talk video @sporeball! Here's the speaker card we'll be sharing to promote your talk! Feel free to share or repost these wherever you'd like! (Let me know if you prefer a different profile picture to be used or something seems off - I'm happy to fix it!)


![Promo - Speaker](https://user-images.githubusercontent.com/607807/112764983-f6b99f00-8fd8-11eb-820e-cfb98abe6fc9.png)

**Comment by pixelyunicorn** [comment]
Thanks for getting us your talk video @sporeball! Here's the speaker card we'll be sharing to promote your talk! Feel free to share or repost these wherever you'd like! (Let me know if you prefer a different profile picture to be used or something seems off - I'm happy to fix it!)

![Promo - Speaker](https://user-images.githubusercontent.com/607807/112764989-ffaa7080-8fd8-11eb-99fb-b0b354efb1a5.png)

**Comment by pixelyunicorn** [comment]
There was a tiny typo in the speaker card (wrong time BST) - here's an updated version!

![Promo - Speaker](https://user-images.githubusercontent.com/607807/112776802-9d6c6280-900e-11eb-97e8-a730c39ea2d8.png)

**Comment by SaraVieira** [comment]
sorry for the notification ,cleaning this and seems this talk has been given

Thank you!
