### ISSUE TITLE
Talk proposal: Painting cute 2D animations with GLSL shaders

### ISSUE THREAD

**Issue by learosema** [queerjs/queerjs-talk-proposals#45]
### Talk title

Painting cute 2D animations with GLSL shaders

### Abstract 

I'm a junior frontend developer and I would love to give an introduction to programming GLSL shaders in WebGL and talk about making animated 2D shapes and combining them in artsy ways. I'll also do some live coding so we will create a little artwork together =).  

Talk duration is about 20 mins. Rough structure of my talk is 
- hi :) 1min
- What are shaders? (5min)
- GLSL Programming language concepts and cheatsheet (4min)
- Live coding via CodeSandbox with a prepared three.js template running a shader (10min)

Example work: https://codepen.io/terabaud/pen/zYBLbNX

### Your name (and pronouns)
Lea Rosema (she / her)
Nickname: terabaud [te:ʁabɔːd]

- [ ] This will be my first tech talk

### Location

I'm based in Hamburg, Germany. Applying for QueerJS @ The Internet. 

### Contact Details

Twitter: @terabaud

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by pixelyunicorn** [comment]
thanks for submitting a talk - we went ahead and put it on our website when we announced our meetup! i'll follow up with you about a week before the meetup to schedule a quick tech check to make sure we can get your talk streaming smoothly! :)

**Comment by pixelyunicorn** [comment]
Hey hi @terabaud! We're just a few short exciting days away from QueerJS!

We just need about 10-15 minutes of your time to do a quick tech check to make sure that screenshare works, we can see/hear you loud and clear, and to answer any questions you may have about QueerJS Online! We will be conducting screensharing & calls over Skype, and Discord can be used as a backup.

In the notes field, please enter your discord tag & skype. I will be available anytime between 9:30am to 11pm EDT / 3:30pm to 5am(+1) CEST, on Sunday/Monday/Tuesday, up until 1 hour before the meetup. I will also be around on Discord as well! (Really sorry for the short notice - I just had my second vaccine dose and I was knocked out all week 🤧)

https://squareup.com/appointments/book/4gzr3gh5duxwbs/QZW4K71GVPJJC/services

**Comment by pixelyunicorn** [comment]
Also, here's the speaker card we'll be sharing to promote your talk! Feel free to share or repost these wherever you'd like! (Let me know if you prefer a different profile picture to be used or something seems off - I'm happy to fix it!)

![Promo - Speaker](https://user-images.githubusercontent.com/607807/112764890-8a3ea000-8fd8-11eb-89a9-7151c36cb699.png)

**Comment by pixelyunicorn** [comment]
There was a tiny typo in the speaker card (wrong time BST) - here's an updated version!

![Promo - Speaker](https://user-images.githubusercontent.com/607807/112776768-86c60b80-900e-11eb-857f-4e7f5f0af597.png)

**Comment by SaraVieira** [comment]
sorry for the notification ,cleaning this and seems this talk has been given

Thank you!
