### ISSUE TITLE
Talk proposal: aspect-oriented programing in the JavaScript world

### ISSUE THREAD

**Issue by thatleda** [queerjs/queerjs-talk-proposals#48]
### Abstract 
There are many programing paradigms that seem vacuous in their description and purpose, and in this talk, I would like to highlight where Aspect-oriented Programing comes from, what its purpose is and the dangers of using it in the browser environment, as well as the problems it can solve. 
### Your name (and pronouns)
Lidiia (Leda) Lazebnikova (she/her)
It would be my first talk, something I'm very excited about but I would appreciate some guidance.

### Location
I live in Schwerin and work in Hamburg. Hamburg or Berlin is somewhere I could speak.

### Contact Details
Leda@hey.com 

### Code of Conduct

- [x ] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by SaraVieira** [comment]
👋 

First of all thank you so much for applying to speak at our berlin event!

We would love to have you ❤️ 

I would more than happy to help with the talk in any way I can, let me know when you would like to schedule something for us to go over it :)

We would pay for your ticket from Hamburg to berlin, do you think you would need accommodation in berlin?

EDIT: Was just looking at trains and it takes 3:30 hours from berlin to Schwerin, so we would definitely set you up somewhere as it's so far away

**Comment by thatleda** [comment]
Hi! 👋🏻 
I am **so** excited! 🎉 
Definitely going to translate my talk into English first and let you know as soon as it's done. How can I reach you for a scheduling thing? Thank you so much for going over it with me!
That's very kind, I really appreciate it!

**Comment by SaraVieira** [comment]
Awesome!! You can email me at hey@queerjs.com or hey@iamsaravieira.com.and we can schedule something :)

I will try to setup a calendly otherwise just email me and super excited 🎉🎉

**Comment by SaraVieira** [comment]
Just added you to the website: https://queerjs.com/berlin-2021

Let me know if it's all good, if so I will announce on Monday :D

**Comment by thatleda** [comment]
Hey,
Looks amazing! 🥲 
Could you make it Leda Lazebnikova, though? It's not really a nickname, just the commonly used version of my name.

**Comment by SaraVieira** [comment]
Of course!

Does this look good: https://queerjs.com/berlin-2021?

**Comment by thatleda** [comment]
Perfection!

**Comment by SaraVieira** [comment]
Awesome!!!

**Comment by SaraVieira** [comment]
sorry for the notification ,cleaning this and seems this talk has been given

Thank you!
