### ISSUE TITLE
Talk proposal: RenJS, a visual novel creator made for writers

### ISSUE THREAD

**Issue by lunafromthemoon** [queerjs/queerjs-talk-proposals#49]
### Talk title

RenJS, a visual novel creator made for writers

### Abstract 

RenJS (https://renjs.net/) is an open source library for making HTML5/Web games of the interactive fiction/visual novel genre. The games are made by writing a script akin to a movie script, that allows for showing/hiding and moving around visual elements, playing music and sound effects and displaying text and dialogue. 
I made RenJS because I wanted to offer a tool to everyone who had a story to tell, regardless of their level of computer literacy and/or equipment. 
I would like to share the story of how I created this library and the amazing community that grew around it, and I would also like to showcase a few of the best RenJS games out there.

### Your name (and pronouns)

Luna (they/them).
First time here.

### Location

Berlin

### Contact Details

lunafromthemoon (twitter/itch/github)

### Code of Conduct

- [ x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by SaraVieira** [comment]
👋 

This is awesome and I love your work! I would love to have you speak! ❤️ 

Let me know if I can add you to the website :)

**Comment by lunafromthemoon** [comment]
Yes, of course. For the talk I would like to know if there will be a projector or something to show a few slides, and if yes, if I should bring my own laptop. Thank you!

**Comment by SaraVieira** [comment]
Hey

There will be a projector and about your laptop you can bring your own or email me the slides and show it on mine, that's completely up to you :)

**Comment by SaraVieira** [comment]
Just added you to the website: queerjs.com/berlin-2021

Let me know if it's all good, if so I will announce on Monday :D

**Comment by SaraVieira** [comment]
Heey

I am sorry to say but we decided that because of the rising COVID numbers we are postponing QueerJS to next year :(

Probably February, would you still like to speak?

**Comment by lunafromthemoon** [comment]
Hey! It makes total sense, and count me in for February!

**Comment by lunafromthemoon** [comment]
hey @SaraVieira I was about to re-send the talk proposal for the next date, so I will just leave this comment here saying I would love to stil give it. thanks!

**Comment by SaraVieira** [comment]
Heeey

I am so sorry this month has been a mess because of all the conferences

I would love to have you speak!

Please let me know if you are still up for it

**Comment by SaraVieira** [comment]
Hoping you would say yes I made the PR that adds you here: https://github.com/queerjs/website/pull/106
And website preview:
https://deploy-preview-106--queerjs.netlify.app/berlin-2022


Sorry again for the delay :(

**Comment by lunafromthemoon** [comment]
Hey, that's great, i definitely will do it! Let me know any details i
should know. Thanks!

**Comment by SaraVieira** [comment]
Niiiice! Merged the PR, all you need to do now is show up on the 30 at 6PM :)

**Comment by lunafromthemoon** [comment]
Hi Sara, here are some slides for my presentation, since I can't take my
own laptop. Thanks!

**Comment by SaraVieira** [comment]
It has been done! :D
