### ISSUE TITLE
Talk proposal: TIC-80 Tiny Computer, or why unbridled creativity without focus on productivity or perfectionism is really important

### ISSUE THREAD

**Issue by pmichk** [queerjs/queerjs-talk-proposals#50]
### Talk title

TIC-80 Tiny Computer, or why unbridled creativity without focus on productivity or perfectionism is really important

### Abstract 

TIC-80 is a fantastic tool for creating games, visualizations and demos. It's simplicity and retro-inspired design make for a fun and engaging experience, while allowing you to create full-fledged projects. But there's more to it than just a coding tool. For me, it rekindled my curiosity and pure enjoyment for making new things. It made me realize that there's inherent value to everything we create, whether a big important project, or a fun little thing we make just to see if we can. And it's that fundamental joy from creating something new that I want to focus on.

### Your name (and pronouns)

Paweł Michalik (any pronouns, most folks use they/them and he/his)

### Location

Belin, in person

### Contact Details

Twitter: @pmichk
Discord: pmichk#5807

### Code of Conduct

- [X] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by SaraVieira** [comment]
Hey

Had never heard of this! Sounds awesome!

You in for speaking on June 30?

**Comment by pmichk** [comment]
Definitely! I'd be happy to present on 30th.

**Comment by SaraVieira** [comment]
I made a new version of the website here: https://deploy-preview-104--queerjs.netlify.app/berlin-2022

Let me know if it looks good and if so I will publish it and announce :partying_face:

**Comment by pmichk** [comment]
Looks fantastic! Thank you <3

**Comment by SaraVieira** [comment]
Perfect! Will publish tomorrow and tag you on the twitters :)

**Comment by SaraVieira** [comment]
It has been done! :D
