### ISSUE TITLE
Talk proposal: Merrily We Scroll Along

### ISSUE THREAD

**Issue by phyllisstein** [queerjs/queerjs-talk-proposals#51]
👋 Hello! This may be a little outré, but I’m very open to tuning and adapting it to better fit your vision for the conference/meetup. The abstract was getting long but I swear on Wilde’s grave there’s more about JavaScript than it sounds like. Very cool group, talk or no. 😬

---

### Talk title
"Merrily We Scroll Along: The Past Is Already Here, It's Just Not Evenly Distributed"

### Abstract 

> **!GREBNETUG**\
> Now, in our time, we are turning Gutenberg around. The technology of movable type created certain structures and practices around the written word. Now the technology of computer screen displays make possible almost _any structure and practices you can imagine_ for the written word.
>
> So now what?
>
> —Ted Nelson, _Computer Lib/Dream Machines_

Primary schools love the drama: Luther striding to the cathedral, hammering his loose pages to the door, and billowing away, a drop of anime sweat dangling from his tonsure. His _95 Theses_ took issue with Papal indulgences—a scheme the Catholic Church cooked up to extract money from the vulnerable by selling certificates of no specific financial or practical value aside from unenforceable claims as to the bearer's state of grace. (It's _one_ web3 joke. Indulge me.) Luther was a riveting, incendiary writer. As their industry took shape, printers could be sure of a profit with a new edition of Luther—guaranteed to sell out—or blank indulgences, for which the Papists paid cash up front.

It was _print_ that tore the Catholic world apart. This was the Protestant Reformation: a two-hundred-odd-year period of human history during which we regularly set one another on fire over whether God speaks Latin.

But print also gave us the Renaissance. A total technology of the preserved word is tectonic: as writing swept through ancient Athens, a language of just 26 characters meant whole new histories, whole new personhoods, could write themselves into the world, and know themselves through the world they wrote. (No fire here, but ask Socrates about the hemlock.)

We're living through another radical transformation in the total technology of text and memory. Within the next decade, the median Android device will achieve the computational power to access our most ambitious work, in all its messy complexity. Some five million people will become more intimate with the web than they—than _we_— could possibly have imagined. How much JavaScript will it take to bring them in as _makers_?

The line of Luther that unmade and remade God: "We are all priests, as many of us as are Christians." We have a new vernacular: we are all speaking JavaScript, as many of us are linked. We need the vernacular Bible. We need the 26-character alphabet. We need new truths. We need to touch the canvas.

Those of us marked by alterity have, historically, been the force that drives these changes. Socrates was the [screamingest queen in antiquity](https://file.garb.ag/3uufjH); [Botticelli's St. Sebastian](https://file.garb.ag/CViI8i) is history's first recorded twink; Black Americans built hip-hop from nothing but [an NYC power outage and expropriated turntables](https://www.amny.com/entertainment/the-1977-nyc-blackout-and-the-hip-hop-spark-that-ignited-soon-after-1-13796834/); [Wendy Carlos](https://file.garb.ag/iIN00S) wove with waves the warp and weft of music. We’re approaching another inflection point in the story of humanity becoming human. How do we understand our responsibility, as technologists, as queers, to that transformation?

We have five years and five millions to figure it out, and we cannot continue talking about performant Amazon shopping experiences. There is only one question worth asking: how do we take an infinite canvas, in an infinite gallery of frames, and hand it to the next five million makers, and the five million after that?

The answer is not going to come from a Luther or a Socrates. We don't need a Musk or an Andreessen. We need one another. It's going to be us.

### Your name (and pronouns)
Daniel P. Shannon (he/him)

I have not attended a workshop. Except for a lightning talk at the monthly BrooklynJS meetup in 2019, I've never spoken at a conference.

### Location
I'm based in Brooklyn, New York, USA. Speaking online would be ideal.

### Contact Details
- Twitter: [`@phyllisstein`](https://twitter.com/phyllisstein)
- Medium: [`@phyllisstein`](https://medium.com/@phyllisstein)
- LinkedIn: [`danielsh1`](https://www.linkedin.com/in/danielsh1/)
- Email: daniel at try dot works

### Code of Conduct
- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by SaraVieira** [comment]
Heeey

First of all thank you so much for submitting a talk! 

We will have a meetup in Berlin that is on June 30, i will ask the space host if we can accomodate online and in person talks 

If so would speaking at our next meetup June 30 be okay for you?

**Comment by phyllisstein** [comment]
It would be wonderful! I’m glad I made it in time. Happy to do whatever I can my end to smooth out the logistics.

**Comment by SaraVieira** [comment]
I think we can just do a zoom call but we will figure it out. I asked the space people and they have the necessary equipement to get this going :)

I made a new version of the website here: https://deploy-preview-104--queerjs.netlify.app/berlin-2022

Let me know if it looks good and if so I will publish it and announce

**Comment by phyllisstein** [comment]
It looks lovely! Thank you! Can I follow up with additional questions about the Zoom thing? I liked the advice on the site about maybe prerecording it.

**Comment by SaraVieira** [comment]
Heeey

Wanna set up a call and we can chat? May be easier, i can also help with the talk in any way

**Comment by phyllisstein** [comment]
Sure thing! Drop me an email and we’ll find a time.

**Comment by SaraVieira** [comment]
It has been done! :D
