### ISSUE TITLE
Talk proposal: Generating Dynamic Open Graph Image for Malaysia's COVID-19 Website

### ISSUE THREAD

**Issue by limhenry** [queerjs/queerjs-talk-proposals#52]
### Talk title

"Generating Dynamic Open Graph Image for Malaysia's COVID-19 Website"

### Abstract 

In this talk, you will learn how I generate the dynamic Open Graph image (og:image) for Malaysia's COVID-19 website - [COVIDNOW](http://covidnow.moh.gov.my/) with node.js and canvas. I will go though the inspiration of this idea as well as some pain points while implementing the feature.

### Your name (and pronouns)

Henry Lim (he/him)

Not first-time speaker. Spoke at a few conferences/meetups in South East Asia (+ one talk in US) before the pandemic. But (hopefully) this will be my first talk in Europe!

### Location

Based in Berlin, Germany. Speaking onsite would be ideal. No travel support required _(as long the event is in Berlin)_.

### Contact Details

- Twitter: [@henrylim96](https://twitter.com/henrylim96)

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by SaraVieira** [comment]
Hey!

This sounds great! Will you be able to speak at the next meetup on the 30?

**Comment by limhenry** [comment]
Yes! I am very ok to speak on that day!

**Comment by limhenry** [comment]
If you need high resolution head shot, feel free to get it from here: https://limhenry.xyz/about#:~:text=Photos

**Comment by SaraVieira** [comment]
Perfect!

You have been added to the website :)

https://queerjs.com/berlin-2022

We actually automatically get the images from your GH profile unless you want me to use another one.

Super excited to see your talk and see you there!

**Comment by limhenry** [comment]
Wohoo!

Thank you. That's perfect!

Looking forward to it. 🤩 See you next week!
