### ISSUE TITLE
Talk proposal: Building a diverse product by leveraging the developer community

### ISSUE THREAD

**Issue by pepicrft** [queerjs/queerjs-talk-proposals#53]
### Talk title

Building a diverse product by leveraging the developer community

### Abstract 

In this talk I’ll share the role a platform mindset plays on adapting a product to different markets and audiences, and how we can leverage Javascript and its ecosystem to make that happen. I’ll give some real examples based on our experience empowering developers to build apps and storefronts for the Shopify ecosystem.

### Your name (and pronouns)

Pedro. He/his

### Location
Berlin

### Contact Details

https://twitter.com/pepicrft
https://github.com/pepicrft
hola@craftweg.com

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by SaraVieira** [comment]
Hey!

Thank you so much! Can you speak on the 30?

**Comment by pepicrft** [comment]
Hey Sara,
It's a bit tight, but I can make it happen.

**Comment by SaraVieira** [comment]
Thank you so much!  We have been struggling to find speakers

Will make sure to add you to the website today

**Comment by pepicrft** [comment]
Hi @SaraVieira,
Would it be possible to change the proposal? With the limited time that I have I think it'll be better if I prepare something around my experience re-writing a CLI in Node. If it's fine I can send you the new proposal, otherwise I can stick to what I already proposed.

**Comment by SaraVieira** [comment]
Hey!

I can also not put anything about what your talk will be and then you do whatever you have. There is no need to announce it before :)

**Comment by SaraVieira** [comment]
Basically what I am saying is, show up, talk about whatever you want and we leave this one open so you can do it at a new event

**Comment by pepicrft** [comment]
> I can also not put anything about what your talk will be and then you do whatever you have. There is no need to announce it before :)

Super!

**Comment by SaraVieira** [comment]
Excited to meet you!

**Comment by SaraVieira** [comment]
It has been done! :D
