### ISSUE TITLE
Talk proposal: Eating your own dog food

### ISSUE THREAD

**Issue by cleptric** [queerjs/queerjs-talk-proposals#54]
### Abstract 

Building SDKs to be used by other developers is all great fun, but at one point, you also need to test out your work in a real application. Does the thing you build work in the wild? Is it easy to use, or did you build something utterly bad?

We'll look at building Sentry's appreciation Slack app called GibPotato, an over-engineered, micro-service-orientated behemoth of CakePHP, Go, and Vue.js built to try out our SDKs using a programming language not part of Sentry's tech stack. 

### Your name (and pronouns)

Michi Hoffmann (he/him)

### Location

I'm based in Vienna and would like to speak during the queerjs @Vienna.
As I'm an employee at Sentry, you can give priority to any none Sentry employees that would like to speak before considering this proposal.

### Contact Details

You can reach me on Discord Cleptric#0001

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by hola-soy-milk** [comment]
Thank you so much for your submission! Looks grand from my end. I'll joyfully add it to the website shortly.

**Comment by SaraVieira** [comment]
sorry for the notification ,cleaning this and seems this talk has been given

Thank you!
