### ISSUE TITLE
Talk proposal: Bootstrapping diverse coding journeys with a web-based game dev course

### ISSUE THREAD

**Issue by jackieklaura** [queerjs/queerjs-talk-proposals#55]
### Abstract 

In this short talk I want to provide some insights into my two [Artful Coding - web-based game development](https://tantemalkah.at/artful-coding/) courses at the University of Applied Arts Vienna and start a discussion about a/typical coding journeys and what "newbie"-friendliness in coding needs to keep in mind. The talk and the guided discussion aim to increase awareness for the socio-technical aspects of coding and coding (self-)education, and to create more diverse journeys into code land.

As the talk integrates an extensive discussion component, I opted for the longer 20-25 min format. Nevertheless, the talk itself can also be put into a shorter 5-10 min lightning talk format, skipping the discussion for a later point.

### Your name (and pronouns)

jackie (ze/hir | she/her)

### Location

I'm based in Vienna and would like to speak during the Queer JS Vienna meetup.

As I already had several talk experiences and opportunities, I would like to pin my proposal to the end of the queue, if other speakers join who had less chance to get onto the stage.

### Contact Details

Discord: @jackie#4955
Mastodon: [@jackie@chaos.social](https://chaos.social/@jackie)
Matrix: @jackie:fuck-the.systems

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by hola-soy-milk** [comment]
@jackieklaura, this looks **amazing**. Thank you so much! I'll joyfully add it to the lineup. Appreciate you!

**Comment by SaraVieira** [comment]
sorry for the notification ,cleaning this and seems this talk has been given

Thank you!
