### ISSUE TITLE
Talk proposal: Weird Web APIs I love to use when making art in the browser

### ISSUE THREAD

**Issue by ninofiliu** [queerjs/queerjs-talk-proposals#63]
### Abstract

Browsers provide a wide array of web APIs for media processing and device communication that are surprisingly powerful and underused. In this talk, I'll explain how I used these unknown gems in my past works as an interactive media artist:

- [First Contact (2023)](https://github.com/ninofiliu/first-contact/): using WebGL, canvases, and open source ML models to create generative art controlled by the spectator's pose viewed from the webcam
- [Sacrifice (2023)](https://www.instagram.com/p/Cyk4GEVorYs/): plugging musical instruments to interactive artsy web app in a few lines of code thanks to WebMIDI
- [Supermosh (2021)](https://supermosh.github.io/): using the WebCodecs API to datamosh in the browser

### Your name (and pronouns)

Nino Filiu (he/they)

This would be my first time speaking and attending :)

### Location

I am Paris-based and would like to speak at the Paris QueerJS of April 23rd 2024

### Contact Details

All my links are on [my website](https://ninofiliu.com/), and you can contact me on either [instagram](https://www.instagram.com/nino.filiu/), or [twitter](https://twitter.com/ninofiliu) 

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by SaraVieira** [comment]
Hey!

Love your work and would love to have you speak! Thank you so much for sending in your proposal!

You okay with us putting you in the website?

**Comment by ninofiliu** [comment]
Yes sure:)

**Comment by SaraVieira** [comment]
Perfect! You are in!

Let me know if you want some help with the talk or anything since this is your first talk 

Always open for a call

**Comment by SaraVieira** [comment]
Question, you okay with me tweeting about you in the queerJS account?

You are on the website btw: https://queerjs.com/paris-2024/

Thank you!!

**Comment by ninofiliu** [comment]
Yes you can tweet about me

I'd love to get past recordings of the talks if there exists somewhere just to get a feel, but I can do without. Otherwise, I'm good:)
