### ISSUE TITLE
Talk proposal: Solving puzzles using javascript

### ISSUE THREAD

**Issue by walaura** [queerjs/queerjs-talk-proposals#66]
### Talk title

Solving puzzles using javascript

### Abstract 

Every time i get super into pen puzzles (stuff like sudoku, picross) i end up building up little algorithms in my mind and then i get distracted thinking how to implement them so i did! come check out my picross solver

### Your name (and pronouns)

Laura González - she/her

### Location

London, this is for the June 27 event!

### Contact Details

[WA pls!](https://wa.me/+447308353087)

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by SaraVieira** [comment]
hell yeah! In the website!

https://github.com/queerjs/queerjs-talk-proposals/issues/66
