### ISSUE TITLE
Talk proposal: Alice in Wonderland: What Happens When We Dream?

### ISSUE THREAD

**Issue by vtenfys** [queerjs/queerjs-talk-proposals#67]
### Talk title

**Alice in Wonderland**: What Happens When We Dream?

### Abstract 

Alice in Wonderland: What Happens When We Dream? is a photo series exploring the nature of dreams and their connection to the real world through a personal narrative centred around my friendships and family. The work inspects questions about fate, existence, and the role of imagination in shaping our understanding of our world.

The photographs themselves capture various elements of the natural world, including plants, trees, rivers and expansive skies. These natural scenes serve as a metaphorical backdrop for the dreamlike exploration of my personal story and reflections on life.

### Your name (and pronouns)

I'm Valerie T. Enfys (they/them). You can think of the [Amy Winehouse song](https://open.spotify.com/track/6kopmMZiyLmw7h66uXcXR7?si=06e7656845004776) 😉

I've worked at [Cleo AI](https://web.meetcleo.com/), [FT](https://www.ft.com/), [Gatsby](https://www.gatsbyjs.com/) and [Happiful](https://happiful.com/); now I [take photos](https://instagram.com/unidentified.systems) for a living

I previously spoke at [QueerJS Cologne](https://queerjs.com/cologne/) (my name back then was [David Bailey](https://en.wikipedia.org/wiki/David_Bailey))

### Location

I'm based around London. I'd like to speak at the [upcoming London event at tldraw](https://queerjs.com/london-2024/)!

### Contact Details

- socials: www.unidentified.systems
- email: val@unidentified.systems

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by SaraVieira** [comment]
Incredible! This sounds like a super fun talk! Adding you to the website

**Comment by SaraVieira** [comment]
You are now live! https://queerjs.com/london-2024/


Thank you so much for wanting to come back to QueerJS :D

**Comment by vtenfys** [comment]
Thank you @SaraVieira! Looking forward!!
