### ISSUE TITLE
Talk proposal: Performance from 0 to 100

### ISSUE THREAD

**Issue by maddhruv** [queerjs/queerjs-talk-proposals#9]
### Talk title
Performance from 0 to 100

### Abstract 
The talk covers how we (ClearTax) brought the performance metrics in lighthouse audits of our most widely used app from a 0 to 90s - app shell architecture, code splitting and lazy loading architecture, proper css modules compilations for faster paints, HTTP2 and services workers caching abilities, client-side storage and web workers implementation to give users a better performance at the first load itself.

### Your name (and pronouns)
Dhruv Jain (He/Him)

### Location
Based in - Bangalore, India
Would Like to speak in any of - (Barcelona|Stockholm|San\ Francisco)

### Contact Details
Twitter - https://twitter.com/maddhruv
Email - dhruvjainpenny@gmail.com

### Code of Conduct

- [x] I've read and agree to the [QueerJS Code of Conduct](https://queerjs.com/code-of-conduct)

**Comment by carolstran** [comment]
Hey @maddhruv 👋 Thanks for being interested in speaking at our meetup. Would you be able to pay for travel yourself or would you need assistance?

If you would need assistance then, unfortunately, wouldn't be able to help in this case 😞 We have a limited budget and flying someone from India to Europe or the US (plus visas, etc) wouldn't be possible for us. Generally speaking, our budget for individual speakers is around 300 EUR. So if there's ever a QueerJS closer to Bangalore, then there's a higher chance we can make it happen 😊

Let me know about the travel and we can figure out the next steps.

**Comment by maddhruv** [comment]
I am not able to pay for my travel, 'cause I have recently started working/earning and don't have enough savings
and I don't think either my employer will be interested in sponsoring my travel.
But anyway LMK if any of my talks gets approved and you have a budget to sponsor

**Comment by carolstran** [comment]
Hey @maddhruv, totally understand. In that case, we won't be able to have you at one of the upcoming QueerJS meetups because the necessary travel would exceed our budget. 

I'm going to close your issues, but we'll keep you in mind if we ever have an event closer to Bangalore 😊
